export { PAGES, DEFAULT_LANG } from './pages.ts'
export type { Lang } from './pages.ts'
export type { StoneType, ProductType, MetalsType, IProduct, IRing, ringsColors } from './goodsType.ts'
export type { IRegister } from './form.ts'
export { APP_ROUTES } from './routes'
