export const APP_ROUTES = {
  HOME: '/',
  STORE: '/store',
  GOODS_DETAIL: (id: string) => `/store/${id}`,
  FAQ: '/faq',
  FAQ_QUESTIONS: '/faq/questions',
  FAQ_DELIVERY: '/faq/delivery',
  FAQ_PAYMENT: '/faq/payment',
  FAQ_CONTACTS: '/faq/contacts',
  ABOUT: '/about',
  PRIVACY: '/privacy',
  OFFER: '/offer',
  ACCOUNT: '/account',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_HISTORY: '/account/purchase-history',
  ACCOUNT_CHOSEN: '/account/chosen',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: '/checkout/success',
  COLLECTIONS: '/collections',
  COLLABORATIONS: '/collaborations',
} as const
